
//this is to prevent angular-meteor.template to fail
Template = {};

angular.module("app", ["angular-meteor"]);

//this is the effective part that is usually generated by blaze/templating
Meteor.startup(function() { $('body').attr({"ng-app":"app","ng-include":"'client/index.ng.html'"}); });

